server:
  port: 8081

mongodbUri: mongodb://admin:admin123@localhost:27017/hacomdb?authSource=admin
mongodbDatabase: "hacomdb"
apiPort: 9898

grpc:
  server:
    port: 6565


mongodb:
  reactive:
    socket-keep-alive: true
    connect-timeout: 10000
    socket-timeout: 10000
  settings:
    minConnectionPoolSize: 5
    maxConnectionPoolSize: 20
    maxConnectionIdleTimeMS: 300000
    maxWaitTimeMS: 10000
    serverSelectionTimeoutMS: 30000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
